// dictionaryService.js - Loads the pre-built, curated dictionary files.
//
// The dictionary ships as small per-length files generated by
// tools/build-dictionary.ps1 (see that script for sources and filtering rules):
//   data/dictionary/common-{3..7}.txt - frequent words, used to build puzzles
//   data/dictionary/valid-{3..7}.txt  - all accepted words (superset of common),
//                                       used to validate bonus words

export const MIN_WORD_LENGTH = 3;
export const MAX_WORD_LENGTH = 7;

const WORD_LENGTHS = Array.from(
    { length: MAX_WORD_LENGTH - MIN_WORD_LENGTH + 1 },
    (_, i) => MIN_WORD_LENGTH + i
);

export class DictionaryService {
    static instance = null;

    static getInstance() {
        if (!DictionaryService.instance) {
            DictionaryService.instance = new DictionaryService();
        }
        return DictionaryService.instance;
    }

    constructor() {
        this.validWords = new Set();
        this.commonWords = new Set();
        this.commonWordsByLength = {};
        this.validWordsByLength = {};
        this.isLoaded = false;
        this.loadPromise = null;
    }

    // Idempotent: concurrent and repeat callers share one load.
    load() {
        if (!this.loadPromise) {
            this.loadPromise = this._loadDictionaries();
        }
        return this.loadPromise;
    }

    async _loadDictionaries() {
        try {
            const [commonLists, validLists] = await Promise.all([
                Promise.all(WORD_LENGTHS.map(len => this._fetchWordList(`data/dictionary/common-${len}.txt`))),
                Promise.all(WORD_LENGTHS.map(len => this._fetchWordList(`data/dictionary/valid-${len}.txt`)))
            ]);

            WORD_LENGTHS.forEach((len, i) => {
                this.commonWordsByLength[len] = commonLists[i];
                this.validWordsByLength[len] = validLists[i];
                commonLists[i].forEach(word => this.commonWords.add(word));
                validLists[i].forEach(word => this.validWords.add(word));
            });

            console.log(`Dictionary loaded: ${this.commonWords.size} common / ${this.validWords.size} valid words`);
        } catch (error) {
            console.error('Failed to load dictionary files, using fallback:', error);
            this._loadFallbackDictionary();
        }

        this.isLoaded = true;
        return true;
    }

    async _fetchWordList(path) {
        const response = await fetch(path);
        if (!response.ok) {
            throw new Error(`${path}: HTTP ${response.status}`);
        }
        const text = await response.text();
        return text.split('\n')
            .map(word => word.trim())
            .filter(word => word.length > 0);
    }

    _loadFallbackDictionary() {
        // Minimal built-in word set so the game still works offline / if fetch fails.
        const fallback = [
            'CAT', 'CATS', 'SAT', 'CAST', 'SEAT', 'EAST', 'EATS', 'CASE', 'ACT', 'ACTS',
            'RAT', 'RATE', 'RATES', 'EAR', 'EARS', 'TEAR', 'TEARS', 'STAR', 'STARE', 'REST',
            'BEAR', 'BEARS', 'BASE', 'BARE', 'BARS', 'BAR', 'ARE', 'ERA', 'SEA', 'ART',
            'PART', 'PARTS', 'TRAP', 'TAPS', 'PAST', 'ARTS', 'RATS', 'PAR', 'TAR', 'TAP',
            'LINE', 'LINES', 'LENS', 'LIES', 'LIE', 'NIL', 'SIN', 'INN', 'ISLE', 'NILE',
            'MAKE', 'MAKES', 'SAME', 'SAKE', 'MASK', 'SEAM', 'MAST', 'MESA', 'ASK', 'ARM',
            'HOUSE', 'HOSE', 'SHOE', 'HUES', 'USE', 'USES', 'SUE', 'HUE', 'SHE', 'HOE',
            'TIME', 'TIMER', 'TIRE', 'TIER', 'MITE', 'TERM', 'RITE', 'TRIM', 'ITEM', 'EMIT',
            'PLAN', 'PLANE', 'LEAN', 'LEAP', 'PANE', 'PALE', 'LANE', 'PEAL', 'PEN', 'NAP',
            'GREAT', 'GATE', 'GEAR', 'RAGE', 'GRATE', 'TAG', 'RAG', 'GET', 'ATE', 'TEA'
        ];

        this.validWords = new Set(fallback);
        this.commonWords = new Set(fallback);
        this.commonWordsByLength = {};
        this.validWordsByLength = {};

        for (const word of fallback) {
            const len = word.length;
            (this.commonWordsByLength[len] ??= []).push(word);
            (this.validWordsByLength[len] ??= []).push(word);
        }
    }

    // --- Lookups -----------------------------------------------------------

    // Is this an accepted English word? (bonus word validation)
    hasWord(word) {
        return this.validWords.has(word.toUpperCase());
    }

    // Is this a common word? (puzzle generation)
    isCommonWord(word) {
        return this.commonWords.has(word.toUpperCase());
    }

    getCommonWordsInLengthRange(minLength, maxLength) {
        const words = [];
        for (let len = minLength; len <= maxLength; len++) {
            words.push(...(this.commonWordsByLength[len] || []));
        }
        return words;
    }

    // Can `word` be assembled from `letters` (respecting duplicates)?
    canMakeWord(word, letters) {
        const counts = {};
        for (const letter of letters) {
            counts[letter] = (counts[letter] || 0) + 1;
        }
        for (const char of word) {
            if (!counts[char]) {
                return false;
            }
            counts[char]--;
        }
        return true;
    }

    findPossibleWords(letters, minLength = MIN_WORD_LENGTH) {
        return this._findWords(this.validWordsByLength, letters, minLength);
    }

    findPossibleCommonWords(letters, minLength = MIN_WORD_LENGTH) {
        return this._findWords(this.commonWordsByLength, letters, minLength);
    }

    _findWords(wordsByLength, letters, minLength) {
        const results = [];
        const maxLength = Math.min(letters.length, MAX_WORD_LENGTH);
        for (let len = minLength; len <= maxLength; len++) {
            for (const word of wordsByLength[len] || []) {
                if (this.canMakeWord(word, letters)) {
                    results.push(word);
                }
            }
        }
        return results;
    }

    getStats() {
        return {
            totalWords: this.validWords.size,
            commonWords: this.commonWords.size,
            isLoaded: this.isLoaded
        };
    }

    isReady() {
        return this.isLoaded;
    }
}
